### PR TITLE
Update requests version

### PR DESCRIPTION
**Pull request by sjdenny**
Remove the version pin on requests (`2.12` is old - Nov 2016).

* Updated URLs for `responses`: some normalisation is done and this was causing the mocked responses to fail.
* The build seems to be broken for python 3.3: see the Travis report for the first commit 4cc573d in this PR.

### CODE REVIEW

**Comment by danpalmer** [comment]
@tushar00jain @marekyggdrasil could we possibly get the build fixed and this merged in? It's causing us some versioning issues and it would be great to stop holding back a package as common as requests.

**Comment by danpalmer** [comment]
@alviezhang hey we were checking our forked repos to see what we could switch back to the main line packages and saw that this was still open. Are there any plans to continue development of Postmen?

**Comment by impanda-cookie** [comment]
@danpalmer thanks, we will fresh Postmen SDK recently.

**Review by alviezhang — APPROVED** [review]

**Comment by PeterJCLaw** [comment]
@alviezhang thanks for merging this; I'm just re-reviewing our forked repos and dependencies to see what we can move back to upstreams on and realised that this hadn't yet been swapped back. Are there any plans to release a version with this fix?

**Comment by PeterJCLaw** [comment]
@tushar00jain @impanda-cookie thanks for merging this, do you know when you might be able to publish an update to PyPI?

**Pull request merged**
